/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;

import java.awt.JobAttributes;
import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class AplikasiInventarisBarangGUI extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiInventarisBarangGUI
     */
    public AplikasiInventarisBarangGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCatat = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        cbJe = new javax.swing.JComboBox<>();
        tfMerek = new javax.swing.JTextField();
        tfUkuran = new javax.swing.JTextField();
        cbTipe = new javax.swing.JComboBox<>();
        cbSpek = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOKO BAN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setText("NO");

        jLabel3.setText("JENIS");

        jLabel4.setText("MEREK");

        jLabel5.setText("UKURAN");

        tbCatat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "JENIS", "MEREK", "UKURAN", "TIPE", "SPEK"
            }
        ));
        jScrollPane1.setViewportView(tbCatat);

        jLabel6.setText("TIPE");

        jLabel7.setText("SPEK");

        cbJe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOTOR", "MOBIL" }));

        tfMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMerekActionPerformed(evt);
            }
        });

        cbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TUBLES", "NON TUBLES" }));

        cbSpek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOFT COMPOUNT", "MEDIUM COMPOUNT", "HARD COMPOUNT" }));

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("TAMBAH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setText("BERSIHKAN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 51));
        jButton4.setText("SIMPAN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 0));
        jButton5.setText("HAPUS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setText("KELUAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 255, 51));
        jButton7.setText("EXPOR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbJe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(41, 41, 41)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbSpek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tfUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 94, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbJe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbSpek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(59, 59, 59)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Mendapatkan model dari tabel yang ada
        DefaultTableModel model = (DefaultTableModel) tbCatat.getModel();
        // Pengecekan apakah kolom input kosong
        if (tfNo.getText () . trim() .equals("") || tfMerek.getText () . trim() .equals("") || tfUkuran.getText () . trim() .equals("")){
        // Menampilkan pesan peringatan jika ada kolom yang kosong   
            JOptionPane.showMessageDialog(null,"Catatan yang anda isi kurang lengkap \n silahkan isi dengan lengkap");      
        }else{
            model.addRow(new Object[]{tfNo.getText(), cbJe.getSelectedItem(), tfMerek.getText(), tfUkuran.getText(), cbTipe.getSelectedItem(),cbSpek.getSelectedItem()});
            // Set ulang nilai input menjadi default atau kosong
            tfNo.setText("");
            cbJe.setSelectedItem("MOTOR");
            tfMerek.setText("");
            tfUkuran.setText("");
            cbTipe.setSelectedItem("TUBLES");
            cbSpek.setSelectedItem("SOFT COMPOUNT");
         // Tampilkan pesan konfirmasi bahwa catatan telah berhasil diinput
            JOptionPane.showMessageDialog(null,"Catatan anda berhasil di input");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Mendapatkan model dari tabel yang ada
        DefaultTableModel model = (DefaultTableModel)tbCatat.getModel ();
        // Memeriksa apakah baris yang dipilih merupakan baris pertama (indeks ke-0)
        if (tbCatat.getSelectedRow()==1){
            // Memeriksa jika jumlah baris pada tabel adalah 0
            if(tbCatat.getRowCount()==0){
             // Menampilkan pesan untuk memilih catatan pertama jika tidak ada baris    
              JOptionPane.showMessageDialog(null, "pilihcatatan yang mau pertama");
            }else{
             // Menampilkan pesan untuk memilih catatan yang ingin disimpan jika kondisi sebelumnya tidak terpenuhi 
            JOptionPane.showMessageDialog(null, "pilihcatatan yang mau di simpan");
            {}}
            }else{
            // Mengubah nilai pada baris yang dipilih dengan nilai-nilai dari input 
            model.setValueAt(tfNo.getText(), tbCatat.getSelectedRow(), 0);
            model.setValueAt(cbJe.getSelectedItem(), tbCatat.getSelectedRow(), 1);
            model.setValueAt(tfMerek.getText(), tbCatat.getSelectedRow(), 2);
            model.setValueAt(tfUkuran.getText(), tbCatat.getSelectedRow(), 3);
            model.setValueAt(cbTipe.getSelectedItem(), tbCatat.getSelectedRow(), 4); 
            model.setValueAt(cbSpek.getSelectedItem(), tbCatat.getSelectedRow(), 5);
            // Menampilkan pesan konfirmasi bahwa catatan sudah diubah 
            JOptionPane.showMessageDialog(null,"catatan sudah diubah");
            // Mengosongkan nilai dari input untuk persiapan input berikutnya 
            tfNo.setText("");
            cbJe.setSelectedItem("sudah di kerjakan");
            tfMerek.setText("");
            tfUkuran.setText("");
            cbTipe.setSelectedItem("berhasil di pilih");
            cbSpek.setSelectedItem("berhasil di pilih");
            
             
            
            
        }
            }{
        }{
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tfMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMerekActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       // Menampilkan dialog konfirmasi dengan pilihan Yes/No dan menyimpan responsnya dalam variabel 'a'
        int a=JOptionPane. showConfirmDialog(null,"apakah anda ingin keluar", "select", JOptionPane.YES_NO_OPTION);
        {
         System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Mengatur ulang nilai-nilai komponen antarmuka pengguna setelah suatu operasi selesai dieksekusi
        tfNo.setText("");
        cbJe.setSelectedItem("MOTOR");
        tfMerek.setText("");
        tfUkuran.setText("");
        cbTipe.setSelectedItem("TUBLES");
        cbSpek.setSelectedItem("SOFT COMPOUNT");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Mendapatkan model dari tabel yang ada  
        DefaultTableModel model = (DefaultTableModel) tbCatat.getModel();
        // Memeriksa apakah tidak ada baris yang dipilih pada tabel  
        if (tbCatat.getSelectedRow ()==-1){
            // Memeriksa jika baris yang dipilih adalah baris pertama (indeks ke-0)
              if (tbCatat.getSelectedRow()==0){
                  // Menampilkan pesan jika pengguna belum memilih catatan 
                  JOptionPane.showMessageDialog(null, "anda belum memilih catatan");
              }else{
                  // Menampilkan pesan untuk memilih catatan jika kondisi sebelumnya tidak terpenuhi 
                  JOptionPane.showMessageDialog(null, "silahkan pilih catatan");
              }
          }else{
              // Mengatur nilai komponen antarmuka pengguna (UI) dengan nilai dari baris yang dipilih pada tabel 
              tfNo.setText(model.getValueAt(tbCatat.getSelectedRow(), 0) .toString());
              cbJe.setSelectedItem(model.getValueAt(tbCatat.getSelectedRow(),1) .toString());
              tfMerek.setText(model.getValueAt(tbCatat.getSelectedRow(), 2).toString());
              tfUkuran.setText(model.getValueAt(tbCatat.getSelectedRow(), 3) .toString());
              cbTipe.setSelectedItem(model.getValueAt(tbCatat.getSelectedRow(),4) .toString());
              cbSpek.setSelectedItem(model.getValueAt(tbCatat.getSelectedRow(),1) .toString());   
          }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Mendapatkan model tabel dari komponen tbCatat
        DefaultTableModel model = (DefaultTableModel) tbCatat.getModel();
        // Memeriksa apakah ada baris yang dipilih pada tabel
        if (tbCatat.getSelectedRow() ==-1) {
            // Memeriksa apakah baris pertama dipilih, jika belum, tampilkan pesan yang sesuai
            if (tbCatat.getSelectedRow()==0){
                JOptionPane.showMessageDialog(null, "pilih catatan yang ingin anda hapus");
            }else{
                JOptionPane.showMessageDialog(null, "pilih catatan yang di hapus");
            }
        }else{
            // Jika baris dipilih, hapus baris tersebut dari tabel
            model.removeRow(tbCatat.getSelectedRow());
            JOptionPane.showMessageDialog(null, "Data catatan berhasil dihapus");
        }
        // Setelah operasi hapus selesai, atur ulang nilai-nilai beberapa komponen UI ke nilai default atau kosong 
        tfNo.setText("");
        cbJe.setSelectedItem("sudah di pilih");
        tfMerek.setText("");
        tfUkuran.setText("");
        cbTipe.setSelectedItem("tipe berhasil di pilih");
        cbSpek.setSelectedItem("spek berhasil di pilih");
        tfNo.requestFocus(); // Memindahkan fokus ke field tfNo untuk input selanjutnya

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            // Membuat objek BufferedWriter untuk menulis ke file "ExportData.txt"
            BufferedWriter bw = new BufferedWriter(new FileWriter("ExportData.txt"));
            
            // Iterasi melalui setiap baris dan kolom tabel untuk mengekspor data ke file teks
            for(int i = 0; i < tbCatat.getRowCount(); i++) { //membaca rows table
                for(int j = 0; j < tbCatat.getColumnCount(); j++) { //membaca column table
                    bw.write(tbCatat.getValueAt(i, j).toString()+" ");// Menulis nilai sel ke file
                }
                bw.newLine();// Menambahkan baris baru setelah setiap baris tabel
            }
           // Menampilkan pesan konfirmasi jika proses ekspor berhasil 
           JOptionPane.showMessageDialog(null, "Data Berhasil Export");
           bw.close(); // Menutup BufferedWriter setelah selesai penggunaan
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());// Menangani kesalahan jika terjadi
        }
    }//GEN-LAST:event_jButton7ActionPerformed
     


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarangGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiInventarisBarangGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbJe;
    private javax.swing.JComboBox<String> cbSpek;
    private javax.swing.JComboBox<String> cbTipe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCatat;
    private javax.swing.JTextField tfMerek;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfUkuran;
    // End of variables declaration//GEN-END:variables
}
